function [fitresult, gof] = createFit_singlesnr(y2d5, z2d5)
%CREATEFIT1(Y2D5,Z2D5)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : y2d5
%      Y Output: z2d5
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Mar-2018 16:30:38


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( y2d5, z2d5 );

% Set up fittype and options.
ft = fittype( 'atan(a*x^2 + b*x +  c)/pi + 0.5', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.489764395788231 0.445586200710899 0.646313010111265];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
fitresult
gof
legend( h, 'z2d5 vs. y2d5', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel y2d5
ylabel z2d5
grid on


