function [fitresult, gof] = singlesnr(y2fit, z2fit)
%CREATEFIT1(Y2D5,Z2D5)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : y2d5
%      Y Output: z2d5
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Mar-2018 16:30:38


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( y2fit, z2fit );

% Set up fittype and options.
ft = fittype( 'atan(a*x^2 + b*x +  c)/pi + 0.5', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.489764395788231 0.445586200710899 0.646313010111265];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

